### ISSUE TITLE
When I run the server, I get IndexError on line 22 of views.py

### ISSUE THREAD

**Issue by johnpc** [cassidoo/snapchat-dashboard#1]
I have tried to run the server and I get an IndexError. Is there some dependency that I have not resolved? 
![Here is a screenshot of the error](https://cloud.githubusercontent.com/assets/4824042/4500149/8a6a99fa-4a8c-11e4-8f10-df8695e57cb8.png)

**Comment by cassidoo** [comment]
Ahh I forgot to add some installation instructions in the README.  I'll do that now.

**Comment by cassidoo** [comment]
@johnpc Try with the new dependencies listed in the README. :)

**Comment by johnpc** [comment]
I have the requirements from 

```
pip install Django
pip install requests 
easy_install pycrypto
```

I still get the IndexError on line 22, same as above.

**Comment by cassidoo** [comment]
Oh dang!  I think I misunderstood this.  So, the reason why this is happening is because I made the assumption that you've downloaded at least three snaps already when that part is run.  So, take that line out first, run it to get a few pics, and then put the line back. :)
