### ISSUE TITLE
Wanting to work on an updated snapchat libary

### ISSUE THREAD

**Issue by Snowlav** [cassidoo/snapchat-dashboard#2]
By doing some research on this repo I see it´s pretty outdated, for example using really old endpoints such as /bq/login

I want to create a new libary to use with the newest version of snapchat, currently 9.2.1.0.
This includes all the new endpoints and a way to avoid detection.

I have both the newest endpoints and the means needed to avoid detection.

Would you like to work with me on this? Please leave a message below with your skype ID.

**Comment by cassidoo** [comment]
Sounds like an awesome project, @Snowlav!!  Sadly I don't really have the time to work on it right now, but I'll def look for your updates. :+1:
